.PHONY: print_val
print_val: hello.elf
	@echo '$@:'
	@echo "ELF_SRCS       " $(ELF_SRCS)
	@echo "OBJ_SRCS       " $(OBJ_SRCS)
	@echo "ASM_SRCS       " $(ASM_SRCS)
	@echo "C_SRCS         " $(C_SRCS)
	@echo "S_UPPER_SRCS   " $(S_UPPER_SRCS)
	@echo "O_SRCS         " $(O_SRCS)
	@echo "OBJS           " $(OBJS)
	@echo "SECONDARY_FLASH" $(SECONDARY_FLASH)
	@echo "SECONDARY_SIZE " $(SECONDARY_SIZE)
	@echo "ASM_DEPS       " $(ASM_DEPS)
	@echo "S_UPPER_DEPS   " $(S_UPPER_DEPS)
	@echo "C_DEPS         " $(C_DEPS)
